databases:
  - name: go-calendar-db
    plan: free
    databaseName: go_calendar

services:
  - type: web
    name: go-pop1-calendar
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: go-calendar-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.11"
