databases:
  - name: go-calendar-db
    plan: free
    databaseName: go_calendar

services:
  - type: web
    name: go-pop1-calendar
    runtime: go
    plan: free
    buildCommand: go mod tidy && go build -o server .
    startCommand: ./server
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: go-calendar-db
          property: connectionString
